apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-lab
data:
  APP_ENV: "lab"
  LOG_LEVEL: "info"
  PORT: "3000"
  HOST: "0.0.0.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: devops-lab
data:
  VITE_API_URL: ""
