apiVersion: v1
kind: Service
metadata:
  name: practica-frontend
  namespace: devops-lab
spec:
  selector:
    app: practica-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
